Gustav revert trailing symbol bug to fix $##0.0 formatting
looker/ssf pull request #5
Opened 2017-11-09 23:06 UTC by Dutchgoose

pulled latest from upstream SheetJS/ssf and then reverted the line that broke number formatting

fixes: #32316

re-opens (on fork) : SheetJS#19

2017-11-09 23:07 UTC, Dutchgoose commented on bits/82_eval.js
> +                    c === 't' && (out[jj].v === '/' || '$€'.indexOf(out[jj].v) > -1 || out[jj].v === ' ' && out[jj+1] != null && out[jj+1].t == '?')
Looks wonky - but 
![screen shot 2017-11-09 at 3 07 09 pm](https://user-images.githubusercontent.com/5461381/32634279-b3970cd6-c55f-11e7-8ad0-f7626e64220c.png)

2017-11-10 19:04 UTC, n8agrin commented
This looks good, but you need to build the package. To do that, you should run the tests. This package has an interesting build system, but the tl;dr is to run these commands in the project directory:

1. `npm install`
2. `npm install -g mocha`
3. `make test`
4. `make -B`

At the end of all that you should have run the tests, they should have all passed, and you should have ended up with a new `ssf.js` file and a new `ssf.flow.js` file in the root directory. You need to `git add` those, commit them and merge them. Again, this is assuming all the tests pass.

2017-11-10 19:05 UTC, n8agrin requested changes
Need to rebuild the package and commit it. Noted in my prior comment.

2017-11-10 21:38 UTC, Dutchgoose commented
<img width="140" alt="screen shot 2017-11-10 at 1 37 54 pm" src="https://user-images.githubusercontent.com/5461381/32679742-6280169a-c61c-11e7-876c-e0ab6d2e5d3b.png">

2017-11-10 21:38 UTC, Dutchgoose commented
@nate done :]

2017-11-10 21:52 UTC, n8agrin approved these changes
🎉

2017-11-10 21:52 UTC, merged